version: '3'

services:
  service1:
    build:
      context: ./service1
    ports:
      - "3000:3000"
    networks:
      - nest_network

  service2:
    build:
      context: ./service2
    ports:
      - "4000:4000"
    networks:
      - nest_network

  service3:
    build:
      context: ./service3
    ports:
      - "5000:5000"
    networks:
      - nest_network

networks:
  nest_network:
    driver: bridge
